# Generated by Django 4.2.8 on 2023-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dia', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255)),
                ('precio_en_letra', models.CharField(max_length=255)),
                ('servicios', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
    ]
