# Generated by Django 5.1.2 on 2024-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_arrendatario', models.CharField(max_length=255)),
                ('ine_arrendatario', models.CharField(max_length=255)),
                ('curp_arrendatario', models.CharField(max_length=255)),
                ('celular_arrendatario', models.CharField(max_length=255)),
                ('fecha_inicio_contrato', models.CharField(max_length=255)),
                ('fecha_vencimiento_contrato', models.CharField(max_length=255)),
                ('renta', models.CharField(default='', max_length=255)),
                ('iva', models.CharField(default='', max_length=255)),
                ('total', models.CharField(default='', max_length=255)),
                ('deposito', models.CharField(default='', max_length=255)),
                ('mantenimiento', models.CharField(default='', max_length=255)),
                ('dia_de_pago', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dia', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255)),
                ('precio_en_letra', models.CharField(max_length=255)),
                ('servicios', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
    ]
