# Generated by Django 4.2.8 on 2024-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_arrendatario', models.CharField(max_length=255)),
                ('ine_arrendatario', models.CharField(max_length=255)),
                ('fecha_inicio_contrato', models.CharField(max_length=255)),
                ('fecha_vencimiento_contrato', models.CharField(max_length=255)),
                ('dia_de_pago', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255)),
                ('precio_en_letra', models.CharField(max_length=255)),
                ('servicios', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
    ]
