# Generated by Django 5.1.2 on 2024-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('local_comercial', 'Local Comercial'), ('departamento', 'Departamento')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
