# Generated by Django 4.2.8 on 2024-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fecha_inicio_contrato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fecha_vencimiento_contrato',
            field=models.DateField(),
        ),
    ]
