# Generated by Django 4.2.8 on 2024-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0003_alter_contract_fecha_inicio_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fecha_inicio_contrato',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fecha_vencimiento_contrato',
            field=models.CharField(max_length=255),
        ),
    ]
