# Generated by Django 5.1.2 on 2024-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0003_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
