# Generated by Django 5.1.2 on 2024-12-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0004_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('local_comercial', 'Local Comercial'), ('departamento', 'Departamento')], default='', max_length=20),
        ),
    ]
