# Generated by Django 5.1.2 on 2024-12-27 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0005_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('local_comercial', 'Local Comercial'), ('departamento', 'Departamento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
