# Generated by Django 5.1.2 on 2024-12-27 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0006_contract_new_id_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='id',
        ),
        migrations.AlterField(
            model_name='contract',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
