# Generated by Django 5.1.2 on 2024-12-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0007_remove_contract_id_alter_contract_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='new_id',
            new_name='id',
        ),
    ]
