# Generated by Django 5.1.2 on 2024-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0008_rename_new_id_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='titulo_arrendatario',
            field=models.CharField(choices=[('SR', 'Sr.'), ('SRA', 'Sra.')], default='SR', max_length=5),
        ),
    ]
