# Generated by Django 5.1.2 on 2024-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0009_contract_titulo_arrendatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='titulo_arrendatario',
            field=models.CharField(choices=[('SR', 'Sr.'), ('SRA', 'Sra.')], max_length=5),
        ),
    ]
