# Generated by Django 5.1.2 on 2024-12-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0010_alter_contract_titulo_arrendatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='giro',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
