# Generated by Django 5.1.2 on 2024-12-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0012_remove_contract_ine_arrendatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='nacionalidad_arrendatario',
            field=models.CharField(choices=[('MX', 'México'), ('AR', 'Argentina'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('ES', 'España'), ('US', 'Estados Unidos'), ('CA', 'Canadá'), ('BR', 'Brasil'), ('FR', 'Francia'), ('DE', 'Alemania'), ('IT', 'Italia'), ('JP', 'Japón'), ('CN', 'China'), ('IN', 'India'), ('RU', 'Rusia'), ('GB', 'Reino Unido'), ('AU', 'Australia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tipo_de_identificacion',
            field=models.CharField(choices=[('IFE', 'IFE'), ('INE', 'INE'), ('pasaporte', 'Pasaporte'), ('tarjeta de residente', 'Tarjeta de residente')], max_length=100),
        ),
    ]
