# Generated by Django 5.1.2 on 2025-10-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0014_alter_contract_dia_de_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
