# Generated by Django 5.1.2 on 2025-10-08 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo_arrendatario', models.CharField(choices=[('SR', 'Sr.'), ('SRA', 'Sra.')], max_length=5)),
                ('nombre_arrendatario', models.CharField(max_length=255)),
                ('nacionalidad_arrendatario', models.CharField(choices=[('MX', 'México'), ('AR', 'Argentina'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('ES', 'España'), ('US', 'Estados Unidos'), ('CA', 'Canadá'), ('BR', 'Brasil'), ('FR', 'Francia'), ('DE', 'Alemania'), ('IT', 'Italia'), ('JP', 'Japón'), ('CN', 'China'), ('IN', 'India'), ('RU', 'Rusia'), ('GB', 'Reino Unido'), ('AU', 'Australia')], max_length=20)),
                ('identificacion_arrendatario', models.CharField(default='', max_length=100)),
                ('tipo_de_identificacion', models.CharField(choices=[('IFE', 'IFE'), ('INE', 'INE'), ('pasaporte', 'Pasaporte'), ('tarjeta de residente', 'Tarjeta de residente')], max_length=100)),
                ('curp_arrendatario', models.CharField(max_length=255)),
                ('celular_arrendatario', models.CharField(max_length=255)),
                ('fecha_inicio_contrato', models.CharField(max_length=255)),
                ('fecha_vencimiento_contrato', models.CharField(max_length=255)),
                ('renta', models.CharField(default='', max_length=255)),
                ('iva', models.CharField(default='', max_length=255)),
                ('total', models.CharField(default='', max_length=255)),
                ('deposito', models.CharField(default='', max_length=255)),
                ('mantenimiento', models.CharField(default='', max_length=255)),
                ('dia_de_pago', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=5)),
                ('local', models.CharField(max_length=255)),
                ('giro', models.CharField(default='', max_length=255)),
                ('contract_type', models.CharField(choices=[('local_comercial', 'Local Comercial'), ('departamento', 'Departamento')], max_length=20)),
            ],
        ),
    ]
